blog/urls.py
from django.urls import path
from . import views # 'dot' means current app directory(blog)

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>', views.PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.CreatePost, name='post-create'),
    path('post/<slug:slug>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<slug:slug>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='about'),
    path('policies/', views.policies, name='policies'),
    path('features/', views.features, name='features'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


# Each model maps to a single database table.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = models.SlugField(max_length=150, unique=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete= models.CASCADE)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})



"""
The related_name argument is useful if you have more complex related class names. For example, if you have a foreign key 
relationship:

class UserMapDataFrame(models.Model):
    user = models.ForeignKey(User)

Now, in order to access UserMapDataFrame objects from the related User, the default call would be 
"User.usermapdataframe_set.all()", which it is quite difficult to read. Using the related_name 
allows you to specify a simpler or more legible name to get the reverse relation. 
In this case, if you specify user = models.ForeignKey(User, related_name='map_data'), 
the call would then be User.map_data.all().

related_name provides you an ability to let Django know how you are going to access Comment model from Post model 
or in general how you can access reverse models which is the whole point in creating ManyToMany fields 
and using ORM in that sense.
"""
class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, blank=True, null=True)
    text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments') #See the 56th line of 'post_detal' template.

    class Meta:
        ordering = ['date_created']

    def __str__(self):
        return '{} by {}'.format(self.text, self.name)


# The migrate command actually applies the migrations to your database.
# আর makemigrations command টি migrations create করে ।

"""
Database migrations kebol field er khetre projujjo. tai field e kuno change anle shekhetre 
remigration kore nite hobe development server theke. onnothay kuno new method jug korar khetre
kebol file tike save dewai enough.
"""

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# from django.contrib.auth.decorators import login_required, user_passes_test (function-based-views er khetre)
from .models import Post, Comment
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView
)

"""
def home(request):
    posts = Post.objects.all().order_by('-date_posted')
    context = {
        "posts": posts
    }
    return render(request, 'blog/home.html', context)
"""

"""
def home(request):
    posts = Post.objects.all().order_by('-date_posted')
    return render(request, 'blog/home.html', {'posts': posts})
"""

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    """ei line ti use kora hoy karon class based view use korle home template er
       for loop hobe "for post in object_list". ei line ti dile "for post in posts" use kora jabe.
       By default, ListView provide the context as object_list."""
    paginate_by = 8

    # Post Search korar jonno ei method.
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            posts = self.model.objects.filter(title__icontains=query)
        else:
            posts = self.model.objects.all()
            return posts



class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
       context = super(PostDetailView, self).get_context_data(**kwargs)
       context['commentform'] = CommentForm()
       return context

    def post(self, request, slug):
       post = get_object_or_404(Post, slug=slug)
       form = CommentForm()

       if request.method == 'POST':
           form = CommentForm(request.POST)

           if form.is_valid():
               # Create "Comment object" but don't save to the database yet.
                comment  = form.save(commit=False)
                # Assign the current post to the comment.
                comment.post = post
                comment.name = self.request.user
                # Save the comment to the database
                comment.save()
                return redirect('blog:post-detail', slug=slug)

       else:
           form = commentform()



@login_required # ei decorator use korle settings e LOGIN_URL = 'login' setup kore dite hobe.
def CreatePost(request):
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.slug = slugify(post.title)
        post.author = request.user
        post.save()
        messages.success(request, f'Congratulations! Your post has been created!')
        return redirect('blog:post-detail', slug=post.slug)

    else:
        form = PostForm()
        
    return render(request, 'blog/post_form.html',{'form':form})



class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False 



class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/' # You should return to home now. Because you have already deleted the post.

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False



def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def policies(request):
    return render(request, 'blog/policies.html', {'title': 'Policies'})


def features(request):
    return render(request, 'blog/features.html', {'title': 'Features'})

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>

<!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->                                              
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<style>

  body {
      background: #eee8ae;
  }

  h1, h3, h4, h5 {
      color: black;
      text-align: center;
  }

  .site-header {
      margin-bottom: 110px;
  }

  .site-header .navbar-expand-md {
      height: 75px;
      background: black;
  }

  .site-header .navbar-brand {
      color: chartreuse;
      font-size: 25px;
      font-style: italic;
  }

  .site-header .navbar-brand:hover {
      background: green;
      color: white;
  }

  .site-header .navbar-nav .nav-link {
      color: cyan;
  }

  .site-header .navbar-nav .nav-link:hover {
      color: yellow;
  }

  .content-section {
      background: #ffffff ; 
      padding: 10px 20px;
      border: 1px solid gray;
      border-radius: 3px;
      margin-bottom: 20px;
  }

  .article-content {
      white-space: pre-line;
      font-size: 18px;
      text-align: justify;
  }

  .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
  }

  .account-img {
      width: 125px;
      height: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
  }

  .account-heading {
      font-size: 2.5rem;
  }

  legend {
      color: black; 
      text-align: center; 
      font-weight: bold; 
      font-size: 27px; 
      font-style: italic;
  }

  p {
      text-align: justify; 
      font-size: 16px;
  }

  .btn-danger {
    background: red;
    color: white;
  }

  .btn-success {
    background: green;
    color: white;
  }

  .btn-outline-success {
    color: green;
  }

  .btn-outline-success:hover {
    background: green;
  }

  .footer-section {
    margin-bottom: 0px;
    width: 100%;
    padding: 35px;
    background: black;
    text-align: center;
    color: white;
  }

</style>

  {% if title %}
    <title>Blog Home - {{ title }}</title>
  {% else %}
    <title>Blog Home</title>
  {% endif %}

  </head>


  <body>

    <!-- Navbar Left Side -->                                                                             
    <header class="site-header">
      <nav class="navbar navbar-expand-md fixed-top">                                                                                              
        <div class="container">                                                                                                     
          <a class="navbar-brand mr-4 mb-2" href="{% url 'blog:home' %}">Blog Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" style="color:deepskyblue; font-weight: lighter; font-size: 18px ;" href="{% url 'blog:about' %}">About</a>
              <a class="nav-item nav-link" style="color:deepskyblue; font-weight: lighter; font-size: 18px ;" href="{% url 'blog:policies' %}">Policies</a>
              <a class="nav-item nav-link" style="color:deepskyblue; font-weight: lighter; font-size: 18px ;" href="{% url 'blog:features' %}">Features</a>    
              <a class="nav-item nav-link" style="color:deepskyblue; font-weight: lighter; font-size: 18px ;" href="{% url 'blog:contact' %}">Contact</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">                                                                                                            
              <form class="form-inline mr-4" method="GET">                                              
                <input class="form-control mr-sm-1" name="q" type="search" placeholder="Search Posts" aria-label="Search" value="{{ request.GET.q }}">
                 <input type="submit" value="Search" class="btn btn-outline-success btn-md my-0 ml-sm-0">
              </form>
              
              {% if user.is_authenticated %}            
                  <a class="nav-item nav-link" href="{% url 'blog:post-create'%}">Create Post</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}                                                                                  
                 <a class=" btn btn-outline-warning btn-lg" href="{% url 'login' %}">Sign In</a>
                 <a class=" btn btn-outline-primary btn-lg ml-2" href="{% url 'register' %}">Sign Up</a>
              {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
          {{ message }}
              </div>
          {% endfor %}
          {% endif %}

    {% block content %} {% endblock content %}

          <div class="mb-4">
            {% if is_paginated %} <!--See the first comment below -->
            {% if page_obj.has_previous %}
                <a class="btn btn-primary mt-5" href="?page=1">First</a>
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}                                                  
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
            {% endif %}
          </div>
        </div>

    {% block sidebar %} {% endblock sidebar %}
  
  </div>
</div>

  <footer>
    <p class="footer-section">&copy;   
       <!-- dynamic year -->
   <script type="text/javascript">
       document.write(new Date().getFullYear());
   </script>
       LocalHost.com, All Rights Reserved
    </p>
  </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  </html>

<!-- 
The code first checks "if pagination is enabled on the current page". If so then it adds next and previous links as appropriate (and the current page number).
-->

<!-- 
The page_obj is a Paginator object that will exist if pagination is being used on the current page. 
It (page_obj) allows you to get all the information about the current page, previous pages, how many pages there are, etc.
-->

blog/templates/blog/contact.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-12">
	<h1>Contact Us</h1>
	<hr class="mb-3 bg-danger">
</div>
<div style="width: 100%; height: 450px; "></div>
{% endblock content %}

blog/templates/blog/home.html
<!DOCTYPE html>
<html>
<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->                                              
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- Social Share Icon Link -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>

  body {
      background: rgb(116, 116, 121);
  }

  h1, h2, h3, h4, h5 {
      color: black;
      text-align: center;
  }

  .site-header {
      margin-bottom: 110px;
  }

  .site-header .navbar-expand-md {
      height: 85px;
      background: black;
  }

  .site-header .navbar-brand {
      padding: 7px 7px;
      color:chartreuse;
      font-size: 25px;
      font-style: italic;
  }

  .site-header .navbar-brand:hover {
      background: green;
      color: white;
  }

  .site-header .navbar-nav .nav-link {
      color: yellow;
      font-weight: bold;
  }

  .site-header .navbar-nav .nav-link:hover {
      color: red;
  }

  .content-section {
      background: #ffffff ; 
      padding: 10px 20px;
      border: 1px solid gray;
      border-radius: 3px;
      margin-bottom: 20px;
  }

  .search {
      margin-right: 55px;
      margin-top: 3px;
  }

  .article-content {
      white-space: pre-line;
      font-size: 18px;
      text-align: justify;
  }

  .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
  }

 .btn-success {
  background: green;
  color: white;
 }

 .btn-success:hover {
   background: green;
   color:yellow;
 }

 .btn-danger {
    background: red;
    color: white;
 }

 .btn-primary {
    color: white;
    background-color: maroon;
    border: 3px solid black;
 }

.btn-primary:hover {
  color: red;
  background-color: black;
  border: 3px solid black;
}

  .fa {
    padding: 14px;
    font-size: 17px;
    width: 45px;
    text-align: center;
    text-decoration: none;
    border-radius: 50%;
  }

  .fa-facebook {
    background: #3B5998;
    color: white;
  }

  .fa-twitter {
    background: #55ACEE;
    color: white;
    margin-left: 2px;
  }

  .footer-section {
    margin-bottom: 0px;
    width: 100%;
    padding: 50px;
    background: maroon;
    text-align: center;
    color: white;
    font-style: italic;
  }

</style>

  {% if title %}
    <title>Blog Home - {{ title }}</title>
  {% else %}
    <title>Blog Home</title>
  {% endif %}

  </head>


  <body>

    <!-- Navbar Left Side -->                                                                             
    <header class="site-header">
      <nav class="navbar navbar-expand-md fixed-top">                                                                                              
        <div class="container">                                                                                                     
          <a class="navbar-brand mr-4 mb-2" href="{% url 'blog:home' %}">Blog Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">                                                                                              
                <a class="nav-item nav-link" style="color: hotpink; font-weight: bold;" href="{% url 'blog:about' %}">About</a>
                <a class="nav-item nav-link" style="color: hotpink; font-weight: bold;" href="{% url 'blog:policies' %}">Policies</a>
                <a class="nav-item nav-link" style="color: hotpink; font-weight: bold;" href="{% url 'blog:features' %}">Features</a>
              </div>
            
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if user.is_authenticated %}
                  <div class="search">
                      <form class="form-inline mr-5" method="GET">
                        <input class="form-control mr-sm-1" name="q" type="search" placeholder="Search Posts" aria-label="Search" value="{{ request.GET.q }}">
                        <input type="submit" value="Search" class="btn btn-outline-warning btn-md my-0 ml-sm-0">
                      </form>
                  </div>

                      <a class="nav-item nav-link" href="{% url 'blog:post-create'%}">Create Post</a>
                      <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                      <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                  <div style="margin-right: 80px; margin-top: 6px;">
                    <form class="form-inline mr-5" method="GET">
                      <input class="form-control mr-sm-1" name="q" type="search" placeholder="Search Posts" aria-label="Search" value="{{ request.GET.q }}">
                      <input type="submit" value="Search" class="btn btn-outline-success btn-md my-0 ml-sm-0">
                    </form>
                  </div>

                    <a class=" btn btn-outline-warning btn-lg" href="{% url 'login' %}">Sign In</a>
                    <a class=" btn btn-outline-primary btn-lg ml-2" href="{% url 'register' %}">Sign Up</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>

        
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              {% endfor %}
            {% endif %}

          {% block content %}
          {% for post in posts %}
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
                <div class="media-body">
                  <div class="article-metada">
                    <h6>{{ post.author }}</h6>
                    <small class="text-muted ml-1"><em>{{ post.date_posted|date:"F d, Y" }}</em></small>
                  </div> <hr>
                  <p class="article-title"><h2>{{ post.title }}</h2></p>
                  <p class="article-content">{{post.content|slice:":420" }}.....</p>
                    <div class="mb-1 text-center">
                      <a href="{% url 'blog:post-detail' slug=post.slug  %}">
                      <button class="btn btn-success"><small><em>See more </em>&raquo;</small></button></a>
                    </div>
                </div>
              </article>
        {% endfor %}
        {% endblock content %}

          <div class="mb-5">
            {% if is_paginated %}<!--See the first comment below -->
            {% if page_obj.has_previous %}
                <a class="btn btn-primary mt-5" href="?page=1">First</a>
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}                                                  
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-primary mt-5" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
            {% endif %}
          </div>
        </div>

    {% block sidebar %}
        <div class="col-md-4">
          <section class="sidebar">
            <h1 style="text-align: center; background: black; color: white; padding: 5px; ">Latest Posts</h1>
            <div class="list-group">                                                                     
                {% for post in posts %}                                                                                                                       
                    <a href="{% url 'blog:post-detail' slug=post.slug %}" class="list-group-item list-group-item-action list-group-item-warning text-dark">
                    {{post}}
                    </a>
                {% endfor %}
            </div>
          </section>
        </div>
    {% endblock sidebar %}
  
  </div>
</div>

<div style="width: 100%; height: 100px; "></div>

<footer class="footer-section">
    <p class="text-center">&copy;   
      <!-- Dynamic Year -->
  <script type="text/javascript">
      document.write(new Date().getFullYear());
  </script>
      LocalHost.com, All Rights Reserved
    </p>
        <a href="https://facebook.com/arafathossain2229" class="fa fa-facebook"></a>
        <a href="https://twitter.com/Arafat_3449" class="fa fa-twitter"></a>
</footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  </html>

<!-- 
The code first checks "if pagination is enabled on the current page". If so then it adds next and previous links as appropriate (and the current page number).
-->

<!-- 
The page_obj is a Paginator object that will exist if pagination is being used on the current page. 
It (page_obj) allows you to get all the information about the current page, previous pages, how many pages there are, etc.
-->

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">																
				<legend class="border-bottom mb-4">Delete Post</legend>
				<h4>Are you sure you want to delete the post "{{ object.title }}"?</h4>
			</fieldset>
			<div class="text-center mb-2">
				<button class="btn btn-danger" type="submit">Yes, I'm sure</button>
				<a class="btn btn-secondary" href="{% url 'blog:post-detail' slug=post.slug %}">No, take me back</a>
			</div>
		</form>
	</div>
	<div style="width: 100%; height: 380px; "></div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
{% endfor %}
{% endif %}

{% block content %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <div>
            <h6>{{ post.author }}</6>
            <small class="text-muted ml-1">{{ post.date_posted }}</small>
          </div>          
          {% if object.author == user %}
            <div class="mt-2">
              <a class="btn btn-success btn-sm mt-1 mb-1" href="{% url 'blog:post-update' slug=post.slug %}">Update</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' slug=post.slug %}">Delete</a>
            </div>
          {% endif %}
        </div>
        <h1 class="article-title">{{ object.title }}</h1>
        <p class="article-content">{{ object.content }}</p>
      </div>
    </article>
     <!-- The DetailView expects that the model name would be 'object' instead of the model's own name. 
      But to use the model name itself is also correct. And standard is to be maintained. That's it! -->

     <div class="col-md-6 card mb-4  mt-5 ">
      <div class="card-body">
        <h1>Leave a comment</h1>
        <hr> 
        {% if user.is_authenticated %}
          <form method="POST">
          {% csrf_token %}
          <table>
          {{ commentform|crispy }}
          </table>
          <button type="submit" class="btn btn-outline-primary">Submit</button>
          </form>
          {% endif %}
      </div>
    </div>

    <div class="col-md-6 card mb-4  mt-3 ">
      <div class="card-body">
        <h2 class="text-center">{{ post.comments.count }} Comments so far </h2> <!-- "comments.count"......'s' is a must -->

        
        {% for comment in post.comments.all %}
          <div class="comments">
          <p class="font-weight-bold">
            {{ comment.name }}                              
            <span class=" text-muted font-weight-normal">
              {{ comment.date_created }}
            </span>
          </p>
          {{ comment.text|linebreaks }}
          </div>
        {% endfor %}
      

      </div>
    </div>
     
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}																			
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Blog Post</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-success" type="submit">Submit Post</button>
			</div>
		</form>
	</div>
	<div style="width: 100%; height: 320px; "></div>
{% endblock content %}